export const OrderStatus = {
    ORDERED: "ORDERED",
    DISPATCHED: "DISPATCHED",
    DELIVERED: "DELIVERED",
};

export const MainOrderStatus = {
    ORDERED: "ORDERED",
    DELIVERED: "DELIVERED",

    TRANSFERED_TO_FABRICCUTTER: "TRANSFERED_TO_FABRICCUTTER",
    TRANSFERED_TO_FABRICCOLLECTOR: "TRANSFERED_TO_FABRICCOLLECTOR",
    TRANSFERED_TO_PATTERNCUTTER: "TRANSFERED_TO_PATTERNCUTTER",
    TRANSFERED_TO_TRIMS: "TRANSFERED_TO_TRIMS",
    TRANSFERED_TO_FACTORYHEAD: "TRANSFERED_TO_FACTORYHEAD",
    TRANSFERED_TO_TAILOR: "TRANSFERED_TO_TAILOR",
    TRANSFERED_TO_QUALITY_CHECKER: "TRANSFERED_TO_QUALITY_CHECKER",
    TRANSFERED_TO_IN_HOUSE: "TRANSFERED_TO_IN_HOUSE",
    TRANSFERED_TO_ALTERATION_TAILOR: "TRANSFERED_TO_ALTERATION_TAILOR",
};
