export const OrderStatus = {
    ORDERED: "ORDERED",
    DISPATCHED: "DISPATCHED",
    DELIVERED: "DELIVERED",
};

export const MainOrderStatus = {
    ORDERED: "ORDERED",
    TRANSFERED_TO_FABRICCUTTER: "TRANSFERED_TO_FABRICCUTTER",
    TRANSFERED_TO_FABRICCOLLECTOR: "TRANSFERED_TO_FABRICCOLLECTOR",
    TRANSFERED_TO_PATTERNCUTTER: "TRANSFERED_TO_PATTERNCUTTER",
    TRANSFERED_TO_TRIMS: "TRANSFERED_TO_TRIMS",
    TRANSFERED_TO_FACTORYHEAD: "TRANSFERED_TO_FACTORYHEAD",
};
