version: '3.8'

services:
  # Main application service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - redis
    environment:
      - MONGOURI=mongodb://mongo:27017/linkedin-scraper
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - NODE_ENV=production
      - ENABLE_HEADLESS=true
      - TZ=UTC
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

  # MongoDB service
  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  # Redis service
  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  mongo-data:
  redis-data: