import express from "express";
import { assignLeadToUser, automaticallyAssignLeadsToSelectedUsers, automaticallyAssignLeadsToUser, changeLeadRating, changeLeadStatus, createNewLead, deleteLead, getLeadById, getLeads } from "../controllers/lead.controller";
import { authorizeJwt } from "../middlewares/auth.middleware";
let router = express.Router();
router.post("/", createNewLead);
router.get("/", getLeads);
router.get("/getById/:id", getLeadById);
router.patch("/assignLeadToUser/:id", assignLeadToUser);
router.patch("/automaticallyAssignLeadsToUser", authorizeJwt, automaticallyAssignLeadsToUser);
router.patch("/automaticallyAssignLeadsToSelectedUsers", authorizeJwt, automaticallyAssignLeadsToSelectedUsers);
router.patch("/changeLeadRating/:id", authorizeJwt, changeLeadRating);
router.patch("/changeLeadStatus/:id", authorizeJwt, changeLeadStatus);
router.delete("/deleteById/:id", deleteLead);
export default router;