import mongoose from "mongoose";

let aboutUsConversion = mongoose.Schema(
    {
        languageId: { type: mongoose.Types.ObjectId },
        languageName: String,
        aboutUs: String,
        aboutUsDescription: String,
        ourVision: String,
        ourVisionDescription: String,
        ourMission: String,
        ourMissionDescription: String,
        whoWeSurve: String,
        agriculturalStakeholders: String,
        agriculturalStakeholdersDescription: String,
        agTechCompanies: String,
        agTechCompaniesDescription: String,
        ourValues: String,
        trustworthy: String,
        trustworthyDescription: String,
        empowering: String,
        empoweringDescription: String,
        bold: String,
        boldDescription: String,
        contactUs: String,
        faq: String,
        fullName: String,
        email: String,
        telephone: String,
        message: String,
        submit: String,
        faq: String,
        whatProductsdoweCoverinourPortfolio: String,
        whatProductsdoweCoverinourPortfolioDescription: String,
        whyareourservicesfreeforfarmers: String,
        whyareourservicesfreeforfarmersDescription: String,
        howdoweearnmoney: String,
        howdoweearnmoneyDescription: String,
        ourOffice: String,
        officeAddress: String,
        officeAddressValue: String,
        phoneEmail: String,
        phoneValue: String,
        emailValue: String,
        officeHours: String,
        officeHoursValue: String,
        byCheckingThis: String,
        andOur: String,
    },
    { timestamps: true }
);
export default mongoose.model("aboutUsConversion", aboutUsConversion);
