import mongoose from "mongoose";

let conversion = mongoose.Schema(
    {
        languageId: { type: mongoose.Types.ObjectId },
        languageName: String,
        other: String,
        /////////new Fields

        seeds: String,
        spices: String,
        feedandForageCrops: String,
        fiber: String,
        industrial: String,

        selectAll: String,

        trialLink: String,
        managerforhandlingsalesleads: String,
        contactPersonDetailsForCeressy: String,
        accountAccessDesctiption: String,
        pleaseenterdetailsofyourcustomers: String,
        pleasementionotherrelevantcrops: String,
        ifyesIstrainingfreeofcost: String,
        protectedcropsgreenhousesnethouses: String,
        startingAt: String,
        seeds: String,
        spices: String,
        feedandForageCrops: String,
        fiber: String,
        industrial: String,
        any: String,
        useCaseStudies: String,
        link: String,
        review: String,
        addnewProduct: String,
        /////Company Overview
        companyOverview: String,
        companyName: String,
        companyEMailID: String,
        website: String,
        companyFoundingDate: String,
        companyHqLocation: String,
        companyDescription: String,
        /////////Company Representatives
        companyRepresentatives: String,
        detailsofproductlisting: String,
        name: String,
        eMailID: String,
        phonenumber: String,
        sameAsCompany: String,



        ///////// countryArr
        country: String,
        austria: String,
        belgium: String,
        bulgaria: String,
        cyprus: String,
        denmark: String,
        spain: String,
        finland: String,
        france: String,
        greece: String,
        hungary: String,
        ireland: String,
        italy: String,
        luxembourg: String,
        malta: String,
        netherlands: String,
        poland: String,
        portugal: String,
        germany: String,
        rumanía: String,
        sweden: String,
        latvia: String,
        estonia: String,
        lithuania: String,
        czechrepublic: String,
        slovakrepublic: String,
        croatia: String,
        slovenia: String,
        albania: String,
        iceland: String,
        liechtenstein: String,
        monaco: String,
        norway: String,
        andorra: String,
        unitedkingdom: String,
        sanmarino: String,
        holysee: String,
        switzerland: String,
        ukraine: String,
        moldova: String,
        belarus: String,
        georgia: String,
        bosniaandherzegovina: String,
        armenia: String,
        russia: String,
        macedonia: String,
        serbia: String,
        montenegro: String,
        turkey: String,
        othercountriesofeurope: String,
        burkinafaso: String,
        angola: String,
        algeria: String,
        benin: String,
        botswana: String,
        burundi: String,
        capeverde: String,
        cameroon: String,
        unionofcomoros: String,
        congo: String,
        ivorycoast: String,
        djibouti: String,
        egytp: String,
        ethiopia: String,
        gabon: String,
        gambia: String,
        ghana: String,
        guinea: String,
        guineabissau: String,
        equatorialguinea: String,
        kenya: String,
        lesotho: String,
        liberia: String,
        libya: String,
        madagascar: String,
        malawi: String,
        mali: String,
        morocco: String,
        mauritius: String,
        mauritania: String,
        mozambique: String,
        namibia: String,
        níger: String,
        nigeria: String,
        centralafricanrepublic: String,
        southafrica: String,
        rwanda: String,
        saotoméandpríncipe: String,
        senegal: String,
        seychelles: String,
        sierraleone: String,
        somalia: String,
        sudan: String,
        swaziland: String,
        tanzania: String,
        chad: String,
        togo: String,
        tunisia: String,
        uganda: String,
        democraticrepublicofthecongo: String,
        zambia: String,
        zimbabwe: String,
        eritrea: String,
        southsudan: String,
        othercountriesofafrica: String,
        canada: String,
        theunitedstatesofamerica: String,
        mexico: String,
        antiguaybarbuda: String,
        bahamas: String,
        barbados: String,
        belize: String,
        costarica: String,
        cuba: String,
        dominique: String,
        elsalvador: String,
        grenada: String,
        guatemala: String,
        haiti: String,
        honduras: String,
        jamaica: String,
        nicaragua: String,
        panama: String,
        saintvincentandthegrenadines: String,
        dominicanrepublic: String,
        trinidadandtobago: String,
        saintlucia: String,
        saintkittsandneviss: String,
        argentina: String,
        bolivia: String,
        brazil: String,
        colombia: String,
        chile: String,
        ecuador: String,
        guyana: String,
        paraguay: String,
        peru: String,
        surinam: String,
        uruguay: String,
        venezuela: String,
        othercountriesofamerica: String,
        afghanistan: String,
        saudiarabia: String,
        bahrain: String,
        bangladesh: String,
        myanmar: String,
        china: String,
        unitedarabemirates: String,
        philippines: String,
        india: String,
        indonesia: String,
        iraq: String,
        iran: String,
        israel: String,
        japan: String,
        jordan: String,
        cambodia: String,
        kuwait: String,
        laos: String,
        lebanon: String,
        malaysia: String,
        maldives: String,
        mongolia: String,
        nepal: String,
        oman: String,
        pakistan: String,
        qatar: String,
        korea: String,
        northkorea: String,
        singapore: String,
        syria: String,
        srilanka: String,
        thailand: String,
        vietnam: String,
        brunei: String,
        marshallislands: String,
        yemen: String,
        azerbaijan: String,
        kazakhstán: String,
        kirgyzstan: String,
        tajikistan: String,
        turkmeinetan: String,
        uzbekistan: String,
        bhutan: String,
        palestineobserverstatenonmemberoftheunitednations: String,
        othercountriesofasia: String,
        australia: String,
        fiji: String,
        newzeland: String,
        papuanewguinea: String,
        solomonislands: String,
        samoa: String,
        tonga: String,
        vanuatu: String,
        micronesia: String,
        tuvalu: String,
        cookislands: String,
        kiribati: String,
        nauru: String,
        palau: String,
        easttimor: String,
        othercountriesofoceania: String,
        ///////////Product Portfolio
        companyProductPortfolio: String,
        productType: String,
        productCount: String,
        productPortfolio: String,
        product: String,
        productName: String,
        farmmanagementsoftware: String,
        others: String,
        product: String,
        ///////language arr
        languageSupported: String,
        languageagnostic: String,
        amharic: String,
        arabic: String,
        bahasaindonesia: String,
        bulgarian: String,
        burmese: String,
        chinese: String,
        croatian: String,
        czech: String,
        danish: String,
        dutch: String,
        english: String,
        finnsih: String,
        french: String,
        german: String,
        hindi: String,
        hungarian: String,
        italian: String,
        khmer: String,
        latvian: String,
        lithuanian: String,
        malagasy: String,
        malay: String,
        polish: String,
        portuguese: String,
        romanian: String,
        russian: String,
        serbian: String,
        slovak: String,
        spanish: String,
        swahili: String,
        swedish: String,
        thai: String,
        turkish: String,
        ukranian: String,
        uzbekistanian: String,
        vietnamese: String,
        ////////////
        shortDescription: String,
        longDescription: String,

        ////////////Feature Checklist
        featureChecklist: String,
        featureSectionDescription: String,
        ////// softwareDescriptionArr
        whatdescribesyoursoftwarethebest: String,
        fieldcropmanagement: String,
        laborManagement: String,
        equipmentmachinerymanagement: String,
        inputmanagement: String,
        waterManagement: String,
        accountingfinanceregulationcompliance: String,
        cropSalesRetail: String,
        precisionApplication: String,
        climateMonitoringAnalysis: String,
        soilsensinganalysis: String,
        diseasepestmanagement: String,


        /////////softwareTypeArr
        whattypeofsoftwaredoyouprovide: String,
        standardizedOnly: String,
        partiallyCustomized: String,
        fullyCustomized: String,

        /////////softwareDataArr
        howdoesyoursoftwaregatherdata: String,
        satellitebasedinsights: String,
        imaginganalyticsviadrones: String,
        ioTSesnors: String,
        manualinputbyusers: String,
        viathirdpartysoftware: String,
        Otherpleasespecify: String,


        /////////farmAdminArr
        farmadmin: String,
        operationsPlanning: String,
        itinerariesplanningandscheduling: String,
        realtimeoperationtracking: String,
        exporttaskstomaterialsandworkers: String,
        generateautomateddocumentation: String,
        reportoftasksandoccupancyrates: String,


        ////////////Account access*(Hierarchy based access (Owner, advisor, worker,…)
        accountaccess: String,
        yes: String,
        no: String,

        /////////usersPerAccountArr
        usersperaccount: String,
        oneuserperaccount: String,
        multipleusersperaccount: String,
        /////////modeOfUseArr
        modeofuse: String,
        onlinemodeonly: String,
        offlinemode: String,
        /////////yieldAnalysisArr
        yieldanalysiscropplanning: String,
        fieldmapping: String,
        geomappingcropscouting: String,
        fieldcropplanningbudgeting: String,
        yieldpredictionforecast: String,
        profitpredictionmaps: String,
        /////////operationalPlanningArr
        operationalplanning: String,
        inputinventorymanagement: String,
        harvestcrewequipmentdeployment: String,
        /////////precisionAgricultureArr
        precisionagriculture: String,
        variablerateapplicationmaps: String,
        variablerateapplicationVRAautomationcontrol: String,
        seedapplicationmonitoring: String,
        /////////weatherForecastArr
        weatherforecast: String,
        satelliteweatherinsights: String,
        weatherstationcompatibility: String,
        /////////soilAndCropHealthArr
        soilCrophealth: String,
        soilsampling: String,
        soildataanalysis: String,
        scouting: String,
        pestdiseasealert: String,
        growthstageanalysis: String,
        /////////farmAnalyticsArr
        infieldanalytics: String,
        cropzones: String,
        topographyanalysis: String,
        realtimefieldmonitoring: String,
        realtimefleettrackingutilization: String,
        /////////fieldAndEquipmentRecordsArr
        fieldequipmentrecords: String,
        fieldrecordkeeping: String,
        equipmentrecords: String,
        /////////harvestAnalysisArr
        harvestanalysissales: String,
        skutaggingtraceabilitytothesource: String,
        harvestreportsinsights: String,
        directsalestocustomers: String,
        orderprocessingtagging: String,
        commoditypricetracking: String,
        realTimedeliverystatusmonitoring: String,
        /////////hardwareAndConnectivityArr
        compatibility: String,
        meteoStationsandsoilsensors: String,
        eRPintegration: String,
        cropAdvisor: String,
        agribusinesssoftwareintegration: String,
        iSOBUScompliance: String,
        /////////accountingArr
        accountingFinanceCompliance: String,
        bookkeeping: String,
        regulationcompliance: String,
        ///////Other features
        otherfeatures: String,



        //////Target Customer
        targetCustomer: String,

        //// marketsServed arr
        marketsserved: String,
        europeanunion: String,
        restofeurope: String,
        africa: String,
        northamerica: String,
        centralamericaandcaribbean: String,
        asia: String,
        oceania: String,
        southamerica: String,

        /////////typesOfFarmsServedArr
        whichtypesoffarmscanyouservewiththisproduct: String,
        fieldcrops: String,
        vegetables: String,
        orchards: String,
        vineyards: String,
        nuts: String,
        fruits: String,
        flowers: String,
        urbanfarms: String,
        nurseries: String,
        groves: String,
        plantations: String,
        livestock: String,
        mixedFarmCropLivestock: String,
        /////////customersArr
        whoareyourcustomers: String,
        agribusinesses: String,
        contractors: String,
        cooperatives: String,
        farmers: String,
        /////////farmSizeArr
        whichfarmsizegrouparebestservedbyyoursolution: String,
        lessthan: String,
        ha: String,
        noteFarmSize: String,
        ///////What types of leads are you most interested in?
        whattypesofleadsareyoumostinterestedin: String,
        relevantcrops: String,
        notecropsserving: String,
        whichsystemisyourFMScompatiblewithListallthatapplies: String,
        whichsystemisyourFMSisnotcompatiblewithListallthatapplies: String,


        //////////Customer Support
        customerSupport: String,
        doyouofferfreetrial: String,
        /////////typeOfCustomerSupportArr
        whattypeofcustomersupportdoyouoffer: String,
        emailhelpdesk: String,
        onlinechat: String,
        phone: String,
        inperson: String,
        doyouprovidetrainingtouseyourproduct: String,
        /////////typeOfTrainingsArr
        whattypeoftrainingsdoyouoffer: String,

        liveonline: String,
        webinars: String,
        documentation: String,
        videos: String,
        viatelephone: String,
        /////////countryWiseCrops
        foragecrops: String,
        cereal: String,
        grasses: String,
        hops: String,
        potatoes: String,
        herbs: String,
        legumes: String,
        corn: String,
        fruit: String,
        rapeseed: String,
        vine: String,
        rice: String,
        turnips: String,
        soybeans: String,
        tobacco: String,
        ornamentals: String,
        oilseeds: String,
        treesandshrubsoutsideforest: String,
        freshherbs: String,
        fodderandsugarbeet: String,
        meadowsandpastures: String,
        growers: String,

        ///////////////////Installation, Set-up & Pricing
        pricingDetails: String,
        installationSetupPricing: String,
        howcanyoursoftwarebeused: String,
        appleIOSappmobile: String,
        androidappmobile: String,
        desktopwebbased: String,

        //////  what is your pricing model?
        whatisyourpricingmodel: String,
        free: String,
        subscription: String,
        onetimelicense: String,
        custompricing: String,

        ////////////Please provide details for pricing
        pleaseprovidedetailsforpricing: String,

        ///
        ifyoucannotsharetheexactpricePleasesharethelogicbehindit: String,
        ////
        averagesetuptimeandinstallationforsoftwareandanewaccount: String,
        ////
        baseproductpricingonetimeandreoccurringfees: String,
        ////
        differentsubscriptionlevelsnamepricingadditionalfeatures: String,
        ////
        additionaladdonstoyourproduct: String,
        ////
        ////
        global: String,
        whoareyourbiggestcompetitorsCompaniesandproductnames: String,
        multipleSelections: String,
        //////Media
        media: String,
        doyouhavethefollowingmediaavailableIfyescouldyoupleaseshareitviaemail: String,
        productvideoandphotoupload: String,
        companylogoupload: String,
        linkstoproductvideosorphotos: String,
        pleaseEnterlinksformedia: String,
        linkstoproductreviewsthatwecanuseonourplatform: String,
        termsConditions: String,
        igivepermissiontolistmycompanysproductonCeressyplatformusingtheinformationprovidedinthislistingform: String,
        ihavereadandagreedtoCeressystermsandconditionsfortheuseoftheceressyplatform: String,
        iwouldliketobeaddedtoCeressynewslettersmarketingpromotionalactivities: String,

        save: String,
        greenHouses: String,
        verticalIndoorFarm: String,
    },
    { timestamps: String, }
);

export default mongoose.model("conversion", conversion);
