import mongoose from "mongoose";

let homePageConversion = mongoose.Schema(
    {
        languageId: { type: mongoose.Types.ObjectId },
        languageName: String,
        heading: String,
        subheading: String,
        findProducts: String,
        searchHere: String,
        findOnCeressy: String,
        farmManagementSoftware: String,
        farmManagementSoftwareDescription: String,
        findOnCeressySectionImageDetail: String,
        founderCeressy: String,
        interactiveTool: String,
        findsolutionsforallyourfarmingneeds: String,
        categories: String,
        selectAll: String,
        soilClimateInsights: String,
        inputMachineryLaborManagement: String,
        fieldManagementCropProtection: String,
        farmAdministrationHarvestSales: String,
        accountingFinanceRegulationCompliance: String,
        fieldCropManagement: String,
        climateMonitoringAnalysis: String,
        inputManagement: String,
        cropSalesRetail: String,
        diseasePestManagement: String,
        laborManagement: String,
        waterManagement: String,
        percisionApplication: String,
        soilSensingAnalysis: String,
        equipmentMachineryManagement: String,
        farmManagementSoftwareBlockLetters: String,
        benefits: String,
        benifit1: String,
        benifit2: String,
        benifit3: String,
        benifit4: String,
        benifit4: String,
        benifit5: String,
        getStarted: String,
        whoWeAre: String,
        whoWeAreDescription: String,
        onestopshop: String,
        onestopshopDescription: String,
        unbiasedlisting: String,
        unbiasedlistingdescription: String,
        fastSearch: String,
        fastSearchDescription: String,
        easyComparison: String,
        easyComparisonDescription: String,
        freetouse: String,
        freetouseDescription: String,
        howItWorks: String,
        howItWorksDescription: String,
        howItWorksHeading1: String,
        howItWorksDescription1: String,
        howItWorksHeading2: String,
        howItWorksDescription2: String,
        howItWorksHeading3: String,
        howItWorksDescription3: String,
        partnerwithus: String,
        contact: String,
        learnMore: String,
    },
    { timestamps: true }
);
export default mongoose.model("homePageConversion", homePageConversion);
