import mongoose from "mongoose";

let productConversion = mongoose.Schema(
    {
        languageId: { type: mongoose.Types.ObjectId },
        languageName: String,
        category: String,
        whatis: String,
        bestFor: String,
        compatibilityAnalysis: String,
        farmType: String,
        user: String,
        farmSize: String,
        hectares: String,
        acres: String,
        cropType: String,
        marketsServed: String,
        languageSupported: String,
        checkFarmCompatibility: String,
        yourResults: String,
        disclaimer: String,
        editInput: String,
        SLIGHTLYCOMPATIBLE: String,
        selected: String,
        farmingNeeds: String,
        features: String,
        yieldanalysiscropplanning: String,
        precisionagriculture: String,
        weatherforecast: String,
        soilCrophealth: String,
        infieldanalytics: String,
        harvestanalysis: String,
        setupInstallationCustomersupport: String,
        modeofuse: String,
        training: String,
        support: String,
        development: String,
        compatibility: String,
        avgsetupcosttime: String,
        comparewithSimilarSoftware: String,
        pricing: String,
        starting: String,
        trialAvailable: String,
        Details: String,
        usecaseStudies: String,
        reviews: String,
        providedBytheVendor: String,
        noreviewsfound: String,
        noUsecasefound: String,
        getaQuote: String,
        startFreeTrial: String,
        bookaDemo: String,
        aboutCompany: String,
        headquarters: String,
        founded: String,
        marketsServed: String,
    },
    { timestamps: true }
);
export default mongoose.model("productConversion", productConversion);
